# Generated by Django 6.0.3 on 2026-03-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('er_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
