# Generated by Django 6.0.3 on 2026-05-13 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('er_generator', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('E-commerce', 'E-commerce'), ('SaaS', 'SaaS'), ('CMS', 'CMS'), ('Education', 'Education'), ('Finance', 'Finance'), ('Social', 'Social'), ('Analytics', 'Analytics'), ('IoT', 'IoT'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=20)),
                ('er_data', models.JSONField()),
                ('sql', models.TextField()),
                ('sql_dialect', models.CharField(default='PostgreSQL', max_length=20)),
                ('fork_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fork_count'],
            },
        ),
        migrations.CreateModel(
            name='TableNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('idea', 'Idea'), ('todo', 'TODO')], default='info', max_length=10)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedschema',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedschema',
            name='fork_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savedschema',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedschema',
            name='sql_dialect',
            field=models.CharField(choices=[('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('SQL Server', 'SQL Server'), ('Oracle', 'Oracle')], default='PostgreSQL', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_tag_per_user'),
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='source_schema',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_template', to='er_generator.savedschema'),
        ),
        migrations.AddField(
            model_name='schematemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='er_generator.tag'),
        ),
        migrations.AddField(
            model_name='tablenote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablenote',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='er_generator.savedschema'),
        ),
        migrations.AddField(
            model_name='tablenote',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='er_generator.schematemplate'),
        ),
        migrations.AddIndex(
            model_name='schematemplate',
            index=models.Index(fields=['category'], name='er_generato_categor_178f80_idx'),
        ),
        migrations.AddIndex(
            model_name='schematemplate',
            index=models.Index(fields=['-fork_count'], name='er_generato_fork_co_e12c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='schematemplate',
            index=models.Index(fields=['-created_at'], name='er_generato_created_2464a3_idx'),
        ),
        migrations.AddIndex(
            model_name='tablenote',
            index=models.Index(fields=['schema', 'table_name'], name='er_generato_schema__df1782_idx'),
        ),
        migrations.AddIndex(
            model_name='tablenote',
            index=models.Index(fields=['template', 'table_name'], name='er_generato_templat_328458_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablenote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schema__isnull', False), ('template__isnull', True)), models.Q(('schema__isnull', True), ('template__isnull', False)), _connector='OR'), name='note_belongs_to_either_schema_or_template'),
        ),
    ]
