import {
  Search,
  Database,
  Tag,
  Pencil,
  Trash2,
  Download,
  Upload,
  Share2,
  Copy,
  Key,
  Link2,
  MessageSquare,
  GitFork,
  ArrowUp,
  ArrowDownUp,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  Monitor,
  X,
  Check,
  CheckCircle,
  CircleAlert,
  PanelLeft,
  Lock,
  ExternalLink,
  StickyNote,
  Bookmark,
  Users,
  Calendar,
  Clock,
  Image as ImageIcon,
  Flag,
  ZoomIn,
  ZoomOut,
  Maximize,
  Loader,
  Plus,
  Minus,
  LayoutGrid,
  List,
  SearchX,
  Mail,
  Sparkles,
  Zap,
  History,
  Folder,
  Shield,
} from 'lucide-react';

export const iconMap = {
  'search': Search,
  'database': Database,
  'tag': Tag,
  'pencil': Pencil,
  'trash': Trash2,
  'download': Download,
  'upload': Upload,
  'share-2': Share2,
  'copy': Copy,
  'key': Key,
  'link-2': Link2,
  'message-square': MessageSquare,
  'git-fork': GitFork,
  'arrow-up': ArrowUp,
  'arrow-down-up': ArrowDownUp,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'monitor': Monitor,
  'x': X,
  'check': Check,
  'check-circle': CheckCircle,
  'circle-alert': CircleAlert,
  'panel-left': PanelLeft,
  'lock': Lock,
  'external-link': ExternalLink,
  'sticky-note': StickyNote,
  'bookmark': Bookmark,
  'users': Users,
  'calendar': Calendar,
  'clock': Clock,
  'image': ImageIcon,
  'flag': Flag,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  'maximize': Maximize,
  'loader': Loader,
  'plus': Plus,
  'minus': Minus,
  'layout-grid': LayoutGrid,
  'list': List,
  'search-x': SearchX,
  'mail': Mail,
  'sparkles': Sparkles,
  'zap': Zap,
  'history': History,
  'folder': Folder,
  'shield': Shield,
} as const;

export type IconName = keyof typeof iconMap;
